### PR TITLE
added the styling for the message view page

### LINKED ISSUE #88: [view messages] Create CSS for view-messages

### PR DESCRIPTION
**Pull request by Orcohen109**
fix #88

### CODE REVIEW

**Comment by lmilbaum** [comment]
@Yarinh55 Please verify if Sapir contributed for this effort. If yes, than she should add a comment to this PR and the issue involved.

**Comment by Yarinh55** [comment]
Hi @lioramilbaum 
@Orcohen109,  Sapir and Tomer worked together on issues #87 #88 #89 #90 
Each one led an issue so the leader will create the PR

**Comment by sapirhe** [comment]
Yes, we did those issues together, me, Or and Tomer

**Comment by lmilbaum** [comment]
@sapirhe I can't add Tamir as assignee. He should add a comment here.

**Review by lmilbaum — APPROVED** [review]
LGTM

**Pull request merged**
