### PR TITLE
Adding Vagrantfile

### PR DESCRIPTION
**Pull request by Yarinh55**

### CODE REVIEW

**Comment by lmilbaum** [comment]
@Yarinh55 Please add in the first comment the link to the issue. (tip) Use the # char.

**Review by lmilbaum — CHANGES_REQUESTED** [review]
Please specify the issue this PR implements

**Comment by Yarinh55** [comment]
Add a vagrantfile open issue link: #3

**Review by lmilbaum — APPROVED** [review]
LGTM
In following PR, please mention the issue # in your first comment.

**Pull request merged**
