### PR TITLE
Viewmessage- messages method 

### LINKED ISSUE #91: [view messages] Add get_messages method
It will get the messages data from DB and display it in view-messages page in chronological order.
Use Messages table.

### PR DESCRIPTION
**Pull request by morbitton**
fix #91 #128 
@Yarinh55 
we talk with nikita and he offered us to open new PR and get around the conflicts from the test branch

### CODE REVIEW

**Comment by lmilbaum** [comment]
@Yarinh55 comment?

**Review by lmilbaum — APPROVED** [review]
LGTM

**Comment by lmilbaum** [comment]
@igoihman can you please verify why CI didn't run on this PR? Not sure I have the permissions.

**Comment by Yarinh55** [comment]
@lioramilbaum Yes I'm on it

**Comment by morbitton** [comment]
@lioramilbaum  if i send here the CI for this issue its better?

**Pull request merged**
