### PR TITLE
Add app.route for messages view

### PR DESCRIPTION
**Pull request by tomer9989**

### CODE REVIEW

**Comment by tomer9989** [comment]
#89

**Review by lmilbaum — CHANGES_REQUESTED** [review]
messages_view.html is missing

**Comment by sapirhe** [comment]
@lioramilbaum  We did this PR together, me, Or Cohen and Tomer Cohen

**Comment by Orcohen109** [comment]
@lioramilbaum 
I did this issue with Sapir Hen and Tomer Cohen

**Pull request closed without merging**
