### PR TITLE
added view message html file

### LINKED ISSUE #87: [view messages] Create HTML view-messages

### PR DESCRIPTION
**Pull request by sapirhe**
fix #87

### CODE REVIEW

**Comment by sapirhe** [comment]
Hi @lioramilbaum, isuue #87 completed. Me, Or and Tomer did it together.

**Review by lmilbaum — CHANGES_REQUESTED** [review]
Have you verified the code with the code in upstream?  The logo file name is not identical. This page should be broken.

**Comment by sapirhe** [comment]
@lioramilbaum  The file I was referring to is the "logo" pic that Or Cohen upload along with the CSS file for the HTML view message. issue #88.

**Comment by lmilbaum** [comment]
Few issues to address:
1. Or and Tomer can not be assigned to this PR because they didn't leave any comment. 
2. Have you verified the PR with the latest changes in upstream?
3. Press the re-review button if the PR is ready for review

**Comment by tomer9989** [comment]
I did it together with Sapir and Or

**Comment by lmilbaum** [comment]
One more comment from Or, so that I can assign the PR

**Comment by Orcohen109** [comment]
@lioramilbaum 
I did this issue with sapir hen

**Review by lmilbaum — APPROVED** [review]
LGTM

**Pull request merged**
