### PR TITLE
Fixed & added the base of the authentication function

### LINKED ISSUE #140: [Authentication] Fix the authentication base function
Since the last authentication function had problems with CI and deleted, write it again and make sure it passes CI

### PR DESCRIPTION
**Pull request by Omeramsc**
fix #140  @lioramilbaum

### CODE REVIEW

**Comment by lmilbaum** [comment]
Will review it after you remove the WIP from the subject

**Comment by nuIISaftey** [comment]
how do i add my contribution to this WIP?

**Comment by Omeramsc** [comment]
@lioramilbaum PR is no longer a WIP. please re-review so the team members will be able to implement their changes ASAP

**Review by lmilbaum — DISMISSED** [review]
LGTM

**Comment by lmilbaum** [comment]
@octopusShiva I am not following the question. Have you contributed to this PR or have you not?

**Comment by nuIISaftey** [comment]
what do you mean by re-review?
what am i searching for?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by lmilbaum** [comment]
@octopusShiva Who are you asking? Is it @Omeramsc or myself? I have lost you.

**Comment by nuIISaftey** [comment]
and yes, i have issued a pr for this , i believe a few weeks ago. however i could not, at that time, integrate it into omer's func

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nuIISaftey** [comment]
disregard that email.. its a response to an email that is no longer valid

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by lmilbaum** [comment]
@octopusShiva I was asking if you contributed for this PR. Have you?

**Comment by nuIISaftey** [comment]
yes pr #104

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lmilbaum** [comment]
@octopusShiva than I removed you from this one

**Comment by nuIISaftey** [comment]
oooh... you were addressing pr #141..
i missed that.. my bad :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Review by lmilbaum — APPROVED** [review]
LGTM

**Pull request merged**
