### PR TITLE
update README.md file

### PR DESCRIPTION
**Pull request by morbitton**
fix #40 #36

### CODE REVIEW

**Review by lmilbaum — CHANGES_REQUESTED** [review]
There is still a problem with the output. You can see how it looks by viewing the file in GitHub.

**Comment by lmilbaum** [comment]
Screen Shot 2019-12-01 at 15 25 57

**Review by lmilbaum — CHANGES_REQUESTED** [review]
There is still a problem with the output. You can see how it looks by viewing the file in GitHub.

**Comment by morbitton** [comment]
@lioramilbaum 
i fix again :)

**Review by lmilbaum — APPROVED** [review]
LGTM

**Pull request merged**
