### PR TITLE
Get the app going

### LINKED ISSUE #162: Adding the layout file
The layout file will serve as the root template for all pages in the Tiger project.
So each update in this file will change the others (inheritance template)

### PR DESCRIPTION
**Pull request by BarakMerdler**
fix #162 #155 #146 #130 #103 #99 #98 #85 #83 #80 #78 #68 #
@lioramilbaum 
get the app going

### CODE REVIEW

**Comment by lmilbaum** [comment]
Add a fix comment

**Comment by lmilbaum** [comment]
There is a similar code in #175

**Comment by BarakMerdler** [comment]
> Add a fix comment

Didn't get it, what needs to be fixed? what comment?

> There is a similar code in #175

Yes, I used the parts that @morbitton wrote

**Comment by BarakMerdler** [comment]
fix #162 #155 #146 #130 #103 #99 #98 #85 #83 #80 #78 #68 #

**Review by lmilbaum — APPROVED** [review]
LGTM

**Pull request merged**
