### PR TITLE
Add ProvisionScript file & edit vagrantfile

### PR DESCRIPTION
**Pull request by Yarinh55**
implement a solution for issue #10 Add a bash provision script when spinning the VM

### CODE REVIEW

**Review by lmilbaum — CHANGES_REQUESTED** [review]
.vagrant folder is a cache directory used by Vagrant. Those files should not be tracked by git. How do we let git know they should be ignored?

**Comment by lmilbaum** [comment]
@Yarinh55 Have you tested that vagrant uses your provision script when you spin the VM?

**Comment by Yarinh55** [comment]
@lioramilbaum I inserted the file name to gitignore file

**Comment by Yarinh55** [comment]
> @Yarinh55 Have you tested that vagrant uses your provision script when you spin the VM?

yes, its working

**Review by lmilbaum — APPROVED** [review]

**Pull request merged**
