### PR TITLE
Issues 1-2 Create HTML and css file

### PR DESCRIPTION
**Pull request by ronbitonn**
By Ron Biton and Noa Aisen

### CODE REVIEW

**Review by lmilbaum — CHANGES_REQUESTED** [review]
Please specify which issues this PR fixes

**Comment by ronbitonn** [comment]
fix #95 
fix #96

**Review by lmilbaum — APPROVED** [review]
LGTM

**Comment by noaAisen** [comment]
Hi Liora, this is the issues that @ronbitonn  and I did together.
in the first message Ron taged me.

**Pull request merged**
